test_that("lorentz_fit() input (types)", {
  expect_error(lorentz_fit(c(1, "2", 3), c(1, 2, 3)))
  expect_error(lorentz_fit(c(1, NA, 3), c(1, 2, 3)))
  expect_error(lorentz_fit(c(1, 2, 3), c(1, "2", 3)))
  expect_error(lorentz_fit(c(1, 2, 3), c(1, Inf, 3)))
  expect_error(lorentz_fit(c(1, 2, 3), c(1, 2)))
  expect_error(lorentz_fit(c(), c()))
  expect_error(lorentz_fit(1, 1, f0_init = "0"))
  expect_error(lorentz_fit(1, 1, f0_init = -Inf))
  expect_error(lorentz_fit(1, 1, f0_init = c(1, 2)))
  expect_error(lorentz_fit(1, 1, gamma_init = "0"))
  expect_error(lorentz_fit(1, 1, gamma_init = NaN))
  expect_error(lorentz_fit(1, 1, gamma_init = c(1, 2)))
  expect_error(lorentz_fit(1, 1, a_init = "0"))
  expect_error(lorentz_fit(1, 1, a_init = NA))
  expect_error(lorentz_fit(1, 1, a_init = c(1, 2)))
})

test_that("lorentz_fit() output (types)", {
  set.seed(100)
  x_test <- seq(-10, 10, length.out = 200)
  y_test <- .lorentz_fn(x_test, f0 = 2, gamma = 3, a = 5)
  y_noisy <- y_test + rnorm(length(y_test), sd = 0.2)
  fit <- lorentz_fit(x_test, y_noisy)

  expect_s3_class(fit, "LorentzFit")
  expect_equal(attr(fit, "nobs"), length(x_test))
  expect_true(
    all(c("f0", "gamma", "a", "residuals", "r2", "original_x", "original_y")
        %in% names(fit))
  )
  expect_true(is.numeric(fit$f0) && is.finite(fit$f0))
  expect_true(is.numeric(fit$gamma) && is.finite(fit$gamma))
  expect_true(is.numeric(fit$a) && is.finite(fit$a))
  expect_true(is.numeric(fit$residuals) && all(is.finite(fit$residuals)))
  expect_true(is.numeric(fit$r2) && is.finite(fit$r2))
  expect_length(fit$f0, 1)
  expect_length(fit$gamma, 1)
  expect_length(fit$a, 1)
  expect_length(fit$residuals, length(x_test))
  expect_length(fit$r2, 1)
  expect_equal(fit$original_x, x_test)
  expect_equal(fit$original_y, y_noisy)
})

test_that("lorentz_fit() recovers known parameters", {
  set.seed(100)
  x_test <- seq(-10, 10, length.out = 200)
  y_test <- .lorentz_fn(x_test, f0 = 2, gamma = 3, a = 5)
  y_noisy <- y_test + rnorm(length(y_test), sd = 0.2)
  fit <- lorentz_fit(x_test, y_noisy)

  expect_equal(fit$f0, 2, tolerance = 0.1)
  expect_equal(fit$gamma, 3, tolerance = 0.1)
  expect_equal(fit$a, 5, tolerance = 0.1)
})

test_that("lorentz_fit() R-squared on noisy data", {
  set.seed(100)
  x_test <- seq(-10, 10, length.out = 200)
  y_test <- .lorentz_fn(x_test, f0 = 2, gamma = 3, a = 5)
  y_noisy <- y_test + rnorm(length(y_test), sd = 0.2)
  fit <- lorentz_fit(x_test, y_noisy)

  expect_true(fit$r2 > 0.9)
})

test_that("lorentz_fit() auto vs manual init converge", {
  set.seed(100)
  x_test <- seq(-10, 10, length.out = 200)
  y_test <- .lorentz_fn(x_test, f0 = 2, gamma = 3, a = 5)
  y_noisy <- y_test + rnorm(length(y_test), sd = 0.2)
  fit <- lorentz_fit(x_test, y_noisy)
  fit_manual <- lorentz_fit(x_test, y_noisy, f0_init = 2, gamma_init = 3, a_init = 5)

  expect_equal(fit$f0, fit_manual$f0, tolerance = 1e-4)
  expect_equal(fit$gamma, fit_manual$gamma, tolerance = 1e-4)
  expect_equal(fit$a, fit_manual$a, tolerance = 1e-4)
})
